// This file is parsed by the makeexport.c program to generate the
// symbol hash table loaded later (from module_hashlist.h)
// Symbols to be exported should be on separate lines. Blank lines and '//' style comments are allowed

// This file contains only symbols to be exported from the GCC library, and is dependant on the ABI version (this is the EABI file)
// For linking modules without including a copy of the GCC library in each module
    __aeabi_uidiv
    __aeabi_idiv
    __aeabi_i2d
    __aeabi_ddiv
    __aeabi_d2iz
    __aeabi_dmul
    __aeabi_uidivmod
    __aeabi_idivmod
    __aeabi_i2f
    __aeabi_f2d
    __aeabi_dadd
    __aeabi_fdiv
    __aeabi_dcmplt
    __aeabi_dcmpgt
    __aeabi_dsub
    __aeabi_d2f
    __aeabi_ui2f
    __aeabi_fmul
    __aeabi_f2uiz
    __bswapsi2
    __aeabi_ui2d
    __aeabi_d2uiz
